import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, basename } from 'path';
import type { SkillSummary, SessionState } from '../types/index.js';

export interface ContextSnapshot {
  projectName: string;
  ide: string;
  sessionState: SessionState | null;
  recentNotes: string;
  skills: SkillSummary[];
  generatedAt: string;
}

export class ContextBuilder {
  private filePath: string;

  constructor(
    private projectRoot: string,
    filename = 'CONTEXT.md'
  ) {
    this.filePath = join(projectRoot, filename);
  }

  build(snapshot: ContextSnapshot): string {
    const skillList =
      snapshot.skills.length > 0
        ? snapshot.skills
            .map((s) => `- **${s.name}** \`${s.version}\` [${s.scope}] — ${s.description}`)
            .join('\n')
        : '_(no skills installed)_';

    const state = snapshot.sessionState;
    const sessionBlock = state
      ? `- **Sprint:** ${state.currentSprint}
- **Task:** ${state.currentTask}
- **Status:** ${state.status}
- **Last updated:** ${state.lastUpdated}`
      : '_No session state found. Run `agentic-skill session start` to initialize._';

    return `# Project Context Snapshot
> Auto-generated by \`agentic-skill context build\`. Do not edit manually.
> Generated: ${snapshot.generatedAt}

---

## Project

- **Name:** ${snapshot.projectName}
- **IDE:** ${snapshot.ide}

---

## Current Session State

${sessionBlock}

---

## Installed Skills (${snapshot.skills.length})

${skillList}

---

## Recent Notes & Decisions

${snapshot.recentNotes}
`;
  }

  write(snapshot: ContextSnapshot): void {
    const content = this.build(snapshot);
    writeFileSync(this.filePath, content, 'utf-8');
  }

  read(): string | null {
    if (!existsSync(this.filePath)) return null;
    return readFileSync(this.filePath, 'utf-8');
  }

  createDefault(): void {
    if (!existsSync(this.filePath)) {
      writeFileSync(
        this.filePath,
        `# Project Context Snapshot

> Run \`agentic-skill context build\` to populate this file.
`,
        'utf-8'
      );
    }
  }

  exists(): boolean {
    return existsSync(this.filePath);
  }

  getProjectName(): string {
    // Try package.json name, fall back to directory name
    const pkgPath = join(this.projectRoot, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as { name?: string };
        if (pkg.name) return pkg.name;
      } catch {
        // ignore
      }
    }
    return basename(this.projectRoot);
  }
}
