import type { AgentContext } from '@agentic-skill/core';

export type { AgentContext };

export interface IIDEAdapter {
  /** Human-readable IDE name */
  readonly ideName: string;

  /** Project-relative path where context is written */
  readonly contextFilePath: string;

  /**
   * Inject agent context so the IDE's AI picks it up.
   * Creates parent directories as needed.
   */
  injectContext(context: AgentContext, projectRoot: string): Promise<void>;

  /**
   * Remove injected context (on session end).
   * Should not throw if file doesn't exist.
   */
  clearContext(projectRoot: string): Promise<void>;

  /**
   * Check if this IDE is present in the given project root.
   * Used for auto-detection.
   */
  isDetected(projectRoot: string): boolean;
}

/** Build the standardised markdown block injected into every IDE */
export function buildContextMarkdown(ctx: AgentContext): string {
  const skillList =
    ctx.skills.length > 0
      ? ctx.skills
          .map((s) => `- **${s.name}** \`${s.version}\` [${s.scope}] — ${s.description}`)
          .join('\n')
      : '_(no skills installed — run `agentic-skill add <skill>`)_';

  const sessionLines = ctx.sessionState.trim()
    ? ctx.sessionState
    : '_No active session. Run `agentic-skill session start`._';

  return `# Agentic Skill System — Session Context
<!-- Auto-generated by agentic-skill CLI. Do not edit manually. -->
<!-- Re-run \`agentic-skill session start\` to refresh. -->

## Current Session State

${sessionLines}

## Project Rules & Conventions

${ctx.rules.trim() || '_No rules file found. Run `agentic-skill init` to create one._'}

## Installed Skills (${ctx.skills.length})

${skillList}

## Recent Notes & Decisions

${ctx.notes.trim() || '_(no notes yet)_'}

## Project Snapshot

${ctx.projectSnapshot.trim() || '_(no context snapshot — run `agentic-skill context build`)_'}
`;
}
